services:
  postgres:
    image: postgres:16
    container_name: incident_postgres
    environment:
      POSTGRES_DB: incident_platform
      POSTGRES_USER: incident
      POSTGRES_PASSWORD: incident
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U incident -d incident_platform"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - incident_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: incident_redis
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  incident_postgres_data: